window.SPEECH_FILES = {
  "pen": "media_speech_v2_00.wav",
  "pencil": "media_speech_v2_01.wav",
  "book": "media_speech_v2_02.wav",
  "notebook": "media_speech_v2_03.wav",
  "bag": "media_speech_v2_04.wav",
  "rubber": "media_speech_v2_05.wav",
  "desk": "media_speech_v2_06.wav",
  "chair": "media_speech_v2_07.wav",
  "board": "media_speech_v2_08.wav",
  "clock": "media_speech_v2_09.wav",
  "laptop": "media_speech_v2_10.wav",
  "what is it": "media_speech_v2_11.wav",
  "today's mission. hello school": "media_speech_v2_12.wav",
  "it's a pen": "media_speech_v2_13.wav",
  "it's a pencil": "media_speech_v2_14.wav",
  "it's a book": "media_speech_v2_15.wav",
  "it's a notebook": "media_speech_v2_16.wav",
  "it's a bag": "media_speech_v2_17.wav",
  "it's a rubber": "media_speech_v2_18.wav",
  "it's a desk": "media_speech_v2_19.wav",
  "it's a chair": "media_speech_v2_20.wav",
  "it's a board": "media_speech_v2_21.wav",
  "it's a clock": "media_speech_v2_22.wav",
  "it's a laptop": "media_speech_v2_23.wav",
  "it's not a desk. it's a chair": "media_speech_v2_24.wav",
  "it's not a notebook. it's a book": "media_speech_v2_25.wav",
  "it's not a pencil. it's a pen": "media_speech_v2_26.wav",
  "it's not a rubber. it's a bag": "media_speech_v2_27.wav",
  "it's not a board. it's a clock": "media_speech_v2_28.wav",
  "it's not a chair. it's a desk": "media_speech_v2_29.wav",
  "it's not a desk": "media_speech_v2_30.wav",
  "it's not a notebook": "media_speech_v2_31.wav",
  "it's not a pencil": "media_speech_v2_32.wav",
  "it's not a rubber": "media_speech_v2_33.wav",
  "it's not a board": "media_speech_v2_34.wav",
  "it's not a chair": "media_speech_v2_35.wav"
};
